{{- if .Values.nordlynx.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: nordlynx-{{ include "chart.fullname" . }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
stringData:
  PRIVATE_KEY: {{ .Values.nordlynx.privateKey }}

{{- end -}}
