apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
{{- with .Values.connectivity.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.connectivity.service.type }}
  ports:
    {{- range .Values.connectivity.ports }}
    {{ if .servicePort }}
    {{- end }}
    - port: {{ .servicePort }}
      targetPort: {{ .name }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name }}
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end  }}
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
